### ISSUE TITLE
Document the derivation of the matrix from calculated coefficients

### ISSUE THREAD

**Issue by AlexisMousseau** [Nemus-Project/magpie-matlab#15]
When you have time, could you write a bit of documentation on the derivation of the matrix structure from the coefficients you get from the symbolic toolbox ?

**Comment by mdphys** [comment]
Hi @AlexisMousseau 

Certainly. Where do you want the documentation to be written? E.g. in the matlab files as comment, in the README here on GH, ...

**Comment by AlexisMousseau** [comment]
That's a good question ... @mhamilt any idea ? I would say the readme because it's not that useful to the user, it's just to understand the science

**Comment by mdphys** [comment]
I'm writing everything in the README. It turns out to be quite useful as markdown is supported (latex, etc)

**Comment by mdphys** [comment]
Wrote an extensive [README.md](orthotropic/README.md) in the orthotropic section
