### ISSUE TITLE
Implementation of hx and hy

### ISSUE THREAD

**Issue by AlexisMousseau** [Nemus-Project/magpie-matlab#3]
With this implementation since this : 

https://github.com/Nemus-Project/magpie-matlab/blob/fac3992d56f8c41fb714ecb8fa413e13e27facf4/magpie.m#L84

is the way to declare Nx and Ny, we are limited to a integer aspect ratio if we want Nx, Ny and h to be consistent. A fix to this would be to implement hx and hy instead of h and to have they as output, whil Nx and Ny should be input. 

It might need to rework the coefficient functions, I invite you to do this together

**Comment by mdphys** [comment]
All done.
